/* Generated by AN DISI Unibo */ 
package it.unibo.creator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Creator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var distanceGreater = true 
				val DIST_MIN = 300
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
									for( i in 0..2 ){ 
						    			createActorDynamically( "firefly", "${i}", false)
						    		}
									val Millis = System.currentTimeMillis()
									val Timer = java.util.Random().nextLong(1000L,2000L)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="receiver",cond=whenDispatch("distance"))
				}	 
				state("receiver") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val distance = payloadArg(0).toInt()
												if (distanceGreater && distance < DIST_MIN){
													distanceGreater = false		
													val Timer = java.util.Random().nextLong(1000L,2000L)
								emit("syncronize", "syncronize($Timer)" ) 
								CommUtils.outred("emesso sync")
								
												} else if (!distanceGreater && distance >= DIST_MIN) {
													distanceGreater = true
								emit("desyncronize", "desyncronize(0)" ) 
								CommUtils.outred("emesso desync")
								
												}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
